### PR TITLE
Enhancement #259

### PR DESCRIPTION
**Pull request by Jazzer008**
Enhancement #259

### CODE REVIEW

**Comment by ash47** [comment]
Looks good, I need to do a proper code review of it though, as a suggestion for how you might do the unique mechanics thing, we can add an entry into the language file:

unique_mechanic_heroname, then in the code, do a $.Localize, if it localizes correctly, ie, the value changes, then add the unique mechanics thing.

You also need to localize all the info, meaning:

<font color=\'#7C7C7C\'>_____________________________________</font><br>';
+    heroStats += '<font color=\'#FFFFFF\'>DAMAGE:</font>

Might become $.Localize('somestring') where 'somestring' is in the language files. As a rule of thumb, try to never hard code any words in, when ever I spot words I've hard coded, will try to localize them.

**Comment by Jazzer008** [comment]
@ash47 I'll get working on those changes

**Comment by Jazzer008** [comment]
@ash47 Ok, changes have been implemented. Suddenly conflicts though.

**Comment by ash47** [comment]
Likely conflicts with the language files.

**Comment by ash47** [comment]
Merged elsewhere.

**Pull request closed without merging**
