### PR TITLE
Essenceshift

### PR DESCRIPTION
**Pull request by ash47**

### CODE REVIEW

**Comment by vaxxvirus** [comment]
So if this got merged, will the new reborn update have it?

**Comment by ash47** [comment]
The workshop addon only gets updated when I push an update, not sure when I will do that, as it always breaks the gamemode for a while when I do, because Volvo doesn't know how to handle symlinks / updates FML

**Comment by vaxxvirus** [comment]
Why not make a separate test mod and upload there to see for yourself if it breaks the game?

**Comment by ash47** [comment]
It breaks the game because the workshop uploading doesn't work correctly.

A sperate mod also doesn't have dedicated servers so it's no different than
testing on my dev server

**Comment by vaxxvirus** [comment]
That's lame, sorry to hear that.

**Pull request merged**
