### PR TITLE
Attribute-specific essence shift

### PR DESCRIPTION
**Pull request by Myrl**
imgpsh_fullsize

### CODE REVIEW

**Comment by vaxxvirus** [comment]
This doesn't really fit LoD considering the fact that they don't use versions of abilities that do something different than vanilla.

**Comment by darklordabc** [comment]
@vaxxvirus, what do you mean? Do you mean we should not add new abilities because original LoD did not?

**Comment by vaxxvirus** [comment]
I didn't mean to insult you, but yes, that's what I mean.

**Comment by darklordabc** [comment]
No insult. But the latest version of LoD I played on WC3 did have some crazy random new abilities in it. This is very moderate compared to whats in that latest LoD I played.

**Comment by ash47** [comment]
I think the main thing is allowing people to turn it off.

**Comment by Myrl** [comment]
I have another version which increases primary attribute instead.

**Comment by vaxxvirus** [comment]
Really?? The WC3 version has crazy shit? I'd love to see it on reborn

**Comment by vaxxvirus** [comment]
I'd like to use these with Focus Fire. No stats left.

**Comment by Jexah** [comment]
Str Shift + Focus Fire = Life Drain on crack.

**Pull request merged**
