### PR TITLE
Modified Respawn System - Maybe Fixed Respawn Bugs?

### PR DESCRIPTION
**Pull request by darklordabc**
I played around with this code, and it _seems_ to have fixed the meepo bug and the recincarnation bug. I cant be sure unless its test ingame. I'm posting this issue just as a suggestion, I don't expect you to merge this as it is, but hopefully it helps you find the bug yourself.

### CODE REVIEW

**Comment by ash47** [comment]
How can you say maybe fixed?

**Comment by darklordabc** [comment]
It works when I test it. But i can't test it in real conditions like 10 players.

**Comment by ash47** [comment]
I think that it is a terrible idea using:

if (type(hero.GetRespawnTime) == "function") then	

This is extremely unsafe and should never be done.
1) Any unit that respawns will be affected by this, this MAY include Roshan and the Courier
2) If functionality is implemented in the future to get the respawn time of NPCs or other units in the future, this code will break and cause issues, and it will be incredibly hard to trace where the issue is

It seems that your change is basically that you check if the unit is reincarnating, if it is, then set a 3 second respawn timer. This is incorrect, IIRC, the aegis and WK ult have a different respawn time.

Your code also doesn't seem to touch the Meepo Clones if the unit isn't reincarnating.

Additionally, you can change the two if conditions to be a single one:

if meepoClone:IsReincarnating() or meepoClone:WillReincarnate() then


I fail to see what you are trying to achieve here.

**Comment by darklordabc** [comment]
I was trying to fix the Meepo Bug and the WK bug. Your right that the code has serious problems, but it does it does get all the Meepo clones, unlike the current code. 

The problem with your code is this part:

                local playerID = hero:GetPlayerID()
                local mainHero = PlayerResource:GetSelectedHeroEntity(playerID)
                if hero == mainHero then

The probem here, is that if a clone is the dead entity, when you compare hero == mainhero, it fails, and thus the script never changes the respawn time. You do have code for when the main hero dies,  BUT when the clone dies, I don't believe this entity killed is called for the main hero, even if he does technically die. The script should check earlier if the dead entity is a clone, and if it is, it should find the prime hero (GetCloneSource() maybe?) and then adjust the prime heros respawn time. Changing the clones respawn time is worthless, its only the main heros respawn time that counts. 

As for why WK bugs out, I dont know. Which is why I used a different method of sorting for finding relevant entities (checking if they have a respawn time), because I thought maybe WK was slipping through somehow.

**Comment by ash47** [comment]
Well, that's another test case I can try, I'll debug and see what happens
when I have some time.

**Comment by darklordabc** [comment]
Doesn't look like this needs to be open anymore

**Pull request closed without merging**
