### PR TITLE
Update addon_english.txt - Improved/Finished tool-tip warnings

### PR DESCRIPTION
**Pull request by darklordabc**
Changed color scheme, added some formatting, added all known buggy ability relationships. Until more ability malfunctions are identified, this job is done (as far as I can tell). 
Example:
image

### CODE REVIEW

**Comment by ash47** [comment]
Looks like it would work and is done well.

**Comment by Jexah** [comment]
Looks good, but I think it's false to say eclipse is useless. It turns day to night for 10 seconds, and when ground targeted with aghs, it also pro ides vision. 

I'll let you know if I remember anything else.

**Comment by ash47** [comment]
I I was thinking that I may make eclipse work without lucent beam, that's how it worked in old LoD. Probably just make it give you lvl1 lucent beam if you don't have lucent beam.

**Comment by Jexah** [comment]
Not sure if that would leave the right impression. For example, player gets level 3 ult, uses it, it appears to work, they think it's working with a relative level of lucent beam, they pick it again next match, they realise it isn't doing correct damage, they came back here and submit an issue. 

If it doesn't actually cast lucent beam at all, then it is obvious what is happening, as it is correct behaviour in Dota 2. Ever played Luna and used ult with level 0 lucent beam?

**Pull request merged**
