### PR TITLE
Set neutral abilities with no upgrade to have 1 lvl max

### PR DESCRIPTION
**Pull request by darklordabc**
#244

### CODE REVIEW

**Comment by ash47** [comment]
You also added a cooldown to consume? Probably shouldn't try to sneak code into a pull request.

**Comment by Jexah** [comment]
http://puu.sh/oLpct/d3dbcd4ba5.png

Doesn't look like he added the cooldown (in this specific commit), he just moved it. Do we know exactly when it was added?

**Comment by ash47** [comment]
Oh, well, the cooldown does not actually have any affect on anything, except, it prevents someone from spamming consume to activate proc spell effects.

**Comment by Jexah** [comment]
http://puu.sh/oLpkP/e4ed4baa10.png

Topkek Ash.

**Comment by Jexah** [comment]
Actually, now that I think about it, it does have an effect. In Dota, you can infest, wait for cooldown on infest and double infest bomb. You can't do that in LoD if the cooldown is 3 seconds, perhaps consider changing the cooldown back to default?

**Comment by ash47** [comment]
Probably

**Comment by darklordabc** [comment]
I didnt add the cooldown to consume.

**Comment by ash47** [comment]
You commenting literally added NOTHING to this. We have already established that.

**Comment by ash47** [comment]
I just thought I'd tell you again that you commenting added nothing, incase the last notification got lost on the interwebs.

**Comment by darklordabc** [comment]
You just left 2 comments that contributed nothing, well played.

**Comment by ash47** [comment]
My comments made sure that you understood that you contributed nothing. This comment explains to you how you are wrong.

**Pull request merged**
