### PR TITLE
Chinese localization

### PR DESCRIPTION
**Pull request by ethereal64**
Took me 3 hours to do, if any1 knows chinese pls let me know if i made any mistake

### CODE REVIEW

**Comment by ash47** [comment]
I have manually merged it, I still need to verify that it works

**Comment by ethereal64** [comment]
is this version ok? i cant wait to play lod in chinese

**Comment by ash47** [comment]
I merged it a long time ago, I just haven't tested it, will add it to the
to-do list, I'm sorry that I forgot

**Comment by ash47** [comment]
I have a high priority issue open https://github.com/ash47/LegendsOfDota/issues/195

**Comment by ash47** [comment]
I assume this is simplificed chinese and not traditional? If so, I can roll it out right now, just need to confirm which kind this is XD

**Comment by ash47** [comment]
@ethereal64

**Comment by ethereal64** [comment]
yes it is

**Comment by ethereal64** [comment]
simplified chinese

**Comment by ash47** [comment]
I have manually merged your code in. Thanks a lot for the contribution.

**Pull request closed without merging**
