### PR TITLE
Suggestion for issue #257

### PR DESCRIPTION
**Pull request by Jazzer008**
[issue #257 ](https://github.com/ash47/LegendsOfDota/issues/257) 

Check if what we're trying to add, from addon_english.txt is a warning and that dota_english.txt contains a similarly named ability.

If so then get the ability description from dota_english.txt and add (append) our warning into that description.

### CODE REVIEW

**Comment by ash47** [comment]
I can modify the script generator to check that when it compiles the
languages

**Comment by ash47** [comment]
I hadn't looked at the code when I commented, you can ignore that comment.

**Comment by ash47** [comment]
Probably worth actually running your code before  you do a pull request :/

Having just pulled down your code and attempting to run, there are syntax error:

if(checkForWarning(key, langIn[lang]){

/\ There is a missing bracket there :/ Based on that, I am going to assume that the code probably hasn't actually been tested at all.

**Comment by Jazzer008** [comment]
@ash47 Looks like I copied from an older file, editing in browser whilst the fork was cloning. Apologies.

I did test the compile, which encountered no issues, however I'm unfamiliar with testing addons using the wsTools console. Point me in the right direction?

**Comment by ash47** [comment]
I checked out your commit, ran it, and it didn't affect the compiled language files. I don't have time to debug why it didn't work at the moment, all I can say is that it didn't work.

**Comment by ash47** [comment]
I implemented this myself because it was much faster than trying to review your code. NOTE: Merging descriptions doesnt actually work in dota.

**Comment by Jazzer008** [comment]
@ash47 Fair enough, are there any particular issues you would like me to take a look at?

**Comment by ash47** [comment]
No. Please only make a pull request if your code has been tested and works.
Each pull request takes 15+ minutes to pull, code review and test,
depending on the size of the pull request of course.

You can do what ever you like, but I won't merge the code if it goes
against the direction of the project, or if it is not implemented correctly
or it is not implemented well.

If you are coding a new feature, you best discuss it via the issues section
as, once again, you might code it perfectly but if it doesn't go in the
direction the project needs to go in, it won't be merged into master.

**Pull request closed without merging**
