### PR TITLE
Fixed formatting (assuming it was broken), clarified some warnings.

### PR DESCRIPTION
**Pull request by darklordabc**

### CODE REVIEW

**Comment by ash47** [comment]
Why would you run stage.bat and then copy the files that it generated if you're just going to copy them again anyways?

Why would you concatenate two strings? '<br> + '<br>' should be '<br><br>'

**Comment by darklordabc** [comment]
Mainly just to keep the alternative setup relevant. It may not even be needed now after the update. 

I've changed the <br> part.

**Comment by darklordabc** [comment]
I tested it, and the same problem occurs. For some reason, if you copy and paste folders with the normal method, it fails to copy the files inside mklink folders sometimes.  So IDK, maybe leave the alternative install as xcopy successfully copies files that get failed to copy sometimes. 
tester2

**Comment by ash47** [comment]
You should really just do a directory junction instead of copying the files
:/

**Comment by darklordabc** [comment]
Removed any changes to altSetup. Can deal with it later.

**Pull request merged**
